### ISSUE TITLE
Compatibility to rubenwardy's food mod

### ISSUE THREAD

**Issue by bell07** [Grizzly-Adam/BBQ-MINETEST-#2]
I see in code you redefines  a lot of "crops" items adding food group. There is an other mod that does the same: https://github.com/rubenwardy/food

Adding groups for other mods is implemented in https://github.com/rubenwardy/food/blob/master/food_basic/support.lua

Basically rubenwardy did prefixed all food groups by "food_"*. (food_tomato instead of tomato).

Maybe you switch to the compatible group names, and do not redefine if the food / food_basic mods are installed?

**Comment by Grizzly-Adam** [comment]
Thanks, I will look into it

**Comment by Grizzly-Adam** [comment]
Fixed.
