### ISSUE TITLE
salt

### ISSUE THREAD

**Issue by chibighost** [Grizzly-Adam/BBQ-MINETEST-#3]
I have found a mod clash between your mod and tenplus's farming redo mod 
sea salt and salt have the same recipe cooking water buckets 
the problem is that farming redo's salt overrides bbq's sea salt leaving many of your recipes un-craftable
if you could create a salt family that includes farming salt as an option for cooking like you did for sugar family that could solve the issue I think

**Comment by Grizzly-Adam** [comment]
I can do that. Thanks.

**Comment by Grizzly-Adam** [comment]
Addressed. Thanks.
